### ISSUE TITLE
run Usage code errors at go ver 1.9

### ISSUE THREAD

**Issue by ihxzihxz** [ponzu-cms/go-client#5]
```
./gdb64.exe --interpreter=mi --args "client.exe" [E:/go/src/github.com/ponzu-cms/go-client/client]
panic: assignment to entry in nil map

goroutine 1 [running]:

net/textproto.MIMEHeader.Set(0x0, 0x67cfd3, 0xd, 0x67f2ae, 0x14)
	d:/go/src/net/textproto/header.go:22 +0x5a
net/http.Header.Set(0x0, 0x67cfd3, 0xd, 0x67f2ae, 0x14)
	d:/go/src/net/http/header.go:31 +0x5a
main.main()
	e:/go/src/github.com/ponzu-cms/go-client/client/main.go:18 +0xc3
```

**Comment by nilslice** [comment]
Hi, what are you running to get this error?
